# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-24 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_product_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_task',
            name='connection_array',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product_task',
            name='node_array',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
