# Generated by Django 3.0.6 on 2020-08-16 07:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0003_auto_20200724_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='create_excel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='excel_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='open_excel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='open_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product_task',
            name='connection_array',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product_task',
            name='node_array',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product_task',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_name', to=settings.AUTH_USER_MODEL),
        ),
    ]
