# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-24 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20200724_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_task',
            name='connection_array',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product_task',
            name='node_array',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
