# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2020-08-16 14:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20200724_1454'),
        ('login', '0004_auto_20200816_1253'),
    ]

    operations = [
    ]
