# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2020-08-17 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_merge_20200816_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_task',
            name='start_node',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
