# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2020-08-17 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_product_task_start_node'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_task',
            name='popup_array',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
