# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2020-08-17 18:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0007_product_task_popup_array'),
    ]

    operations = [
        migrations.CreateModel(
            name='Send_Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_to', models.CharField(max_length=300)),
                ('email_subject', models.CharField(max_length=300)),
                ('msg', models.TextField()),
                ('active', models.BooleanField()),
                ('user_action', models.CharField(max_length=300)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('Product_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='login.Product_Task')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Send_Email', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
