# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2020-08-17 19:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_auto_20200817_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='send_email',
            name='Product_id',
        ),
        migrations.AddField(
            model_name='create_excel',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Create_Project', to='login.Product_Task'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='open_excel',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Open_Project', to='login.Product_Task'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='send_email',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Send_Project', to='login.Product_Task'),
            preserve_default=False,
        ),
    ]
